export type Topic = {
  slug: string;
  name: string;
  also_known_as: string;
  meta_description: string;
  family_slug: string;
  product_slug: string;
  category: string;
  overview: string[];
  mechanism: string[];
  research_applications: string[];
  key_facts: { label: string; value: string }[];
};

export const TOPICS: Topic[] = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    also_known_as: "Body Protection Compound 157, PL 14736",
    meta_description:
      "BPC-157 (Body Protection Compound 157) is a synthetic pentadecapeptide derived from a protective protein found in gastric juice. Research literature documents its effects on angiogenesis, tissue repair, and gut epithelial integrity.",
    family_slug: "tissue-repair-peptides",
    product_slug: "bpc-157",
    category: "Regeneration",
    overview: [
      "BPC-157 is a 15-amino-acid peptide sequence derived from a larger protein isolated from human gastric juice. Its systematic name, Body Protection Compound 157, reflects the protective properties observed in early gastric physiology research. Unlike endogenous gastric peptides that function locally, BPC-157 has been studied for systemic effects in animal models across multiple organ systems.",
      "Research published over the past three decades has examined BPC-157 in the context of wound healing, angiogenesis, and gastrointestinal mucosal repair. Studies in rodent models have documented accelerated closure of cutaneous wounds, tendon-to-bone repair, and intestinal anastomosis healing. The compound appears to upregulate growth factor expression, including VEGF and EGF receptor signaling, which investigators have proposed as a mechanism for its observed pro-regenerative effects.",
      "A notable feature of BPC-157 in preclinical research is its stability in aqueous solution and apparent resistance to degradation in the gastric environment — properties that make it a useful research tool for studying mucosal protection pathways. It has been investigated in models of NSAID-induced gastric lesions, inflammatory bowel models, and intestinal fistula repair, with consistent findings of accelerated mucosal restitution.",
      "All published research on BPC-157 has been conducted in vitro or in animal models. The compound is not approved for human therapeutic use and is sold strictly for laboratory and research applications. Researchers working with BPC-157 should review current literature on its receptor interactions with the NO-cGMP pathway and its influence on FAK-paxillin signaling, which are areas of active mechanistic investigation.",
    ],
    mechanism: [
      "BPC-157 does not bind a single well-characterized receptor. Current research points to interaction with the nitric oxide (NO) system — specifically, modulation of eNOS activity and downstream cGMP signaling — as a central mechanistic pathway. In endothelial cell cultures, BPC-157 has been shown to promote tube formation and VEGFR2 phosphorylation, consistent with a pro-angiogenic role.",
      "At the intracellular level, investigators have reported BPC-157-associated changes in FAK (focal adhesion kinase) and paxillin phosphorylation, suggesting effects on cytoskeletal organization relevant to cell migration during wound closure. Research has also identified interactions with the dopaminergic and serotonergic systems in CNS-related studies, though these pathways remain less characterized than the peripheral tissue-repair literature.",
    ],
    research_applications: [
      "Gastrointestinal mucosal repair and gut epithelial integrity models",
      "Tendon-to-bone repair and musculoskeletal wound healing studies",
      "Angiogenesis and VEGF pathway research",
      "Nitric oxide system modulation studies",
      "Inflammatory bowel disease animal models",
      "Neuroprotection and CNS recovery models (emerging research area)",
    ],
    key_facts: [
      { label: "Sequence", value: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val" },
      { label: "Length", value: "15 amino acids" },
      { label: "Molecular Weight", value: "1,419.5 Da" },
      { label: "Origin", value: "Derived from human gastric juice protein" },
      { label: "Stability", value: "Stable in aqueous solution; gastric acid resistant" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "tb-500",
    name: "TB-500",
    also_known_as: "Thymosin Beta-4, Tβ4",
    meta_description:
      "TB-500 is a synthetic version of Thymosin Beta-4, an endogenous 43-amino-acid peptide involved in actin sequestration, angiogenesis, and tissue repair. Research documents its role in wound healing and inflammatory modulation.",
    family_slug: "tissue-repair-peptides",
    product_slug: "tb-500",
    category: "Regeneration",
    overview: [
      "Thymosin Beta-4 (Tβ4), the endogenous protein on which TB-500 is based, was originally isolated from thymic extracts in the 1960s. It belongs to the beta-thymosin family of actin-monomer-sequestering proteins and is one of the most abundant intracellular peptides in mammals, present at high concentrations in platelets, wound fluid, and inflammatory cells. TB-500 is a synthetic peptide corresponding to the full 43-amino-acid sequence of Tβ4.",
      "The primary biochemical function of Thymosin Beta-4 is regulation of G-actin (globular actin) availability. By sequestering actin monomers, Tβ4 modulates the dynamic assembly and disassembly of actin filaments — a process critical to cell migration, morphology, and division. This actin-regulatory function underlies many of the downstream effects observed in wound healing research, where cell migration is essential for tissue restitution.",
      "Research in animal models has documented TB-500's effects across multiple tissue types. Studies report accelerated repair of cardiac tissue following myocardial injury, improved tendon healing, corneal wound closure, and promotion of hair follicle keratinocyte migration. TB-500 has also been investigated in models of multiple sclerosis, where it appeared to promote oligodendrocyte survival and remyelination — findings that have generated interest in neuroprotection research.",
      "TB-500 is offered for research use only and has not been approved for clinical therapeutic applications. Investigators interested in actin dynamics, wound healing models, or angiogenesis research will find an extensive primary literature base, including work by Huff, Bhatt, and Goldstein documenting structure-activity relationships within the Tβ4 sequence.",
    ],
    mechanism: [
      "The central mechanism of Thymosin Beta-4 involves its LKKTET actin-binding domain, which sequesters G-actin and thereby shifts the actin equilibrium toward a more migratory, dynamic cytoskeletal state. Beyond actin regulation, Tβ4 has been shown to activate ILK (integrin-linked kinase), which mediates Akt phosphorylation and downstream pro-survival signaling.",
      "In vascular research, TB-500 promotes endothelial cell migration and tube formation through mechanisms involving VEGF and MMPs. Research has also identified a nuclear role for Tβ4 in transcriptional regulation, where it appears to interact with PINCH and α-parvin to influence focal adhesion assembly and gene expression programs associated with tissue remodeling.",
    ],
    research_applications: [
      "Actin dynamics and cytoskeletal biology research",
      "Cardiac tissue repair and myocardial regeneration models",
      "Angiogenesis and endothelial migration studies",
      "Corneal wound closure research",
      "Tendon and musculoskeletal healing models",
      "Neuroprotection and remyelination studies",
    ],
    key_facts: [
      { label: "Sequence Length", value: "43 amino acids" },
      { label: "Molecular Weight", value: "4,963 Da" },
      { label: "Endogenous Source", value: "Thymic tissue, platelets, wound fluid" },
      { label: "Key Domain", value: "LKKTET actin-binding motif" },
      { label: "Molecular Target", value: "G-actin, ILK, PINCH" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    also_known_as: "Copper Peptide GHK, Glycyl-L-histidyl-L-lysine copper",
    meta_description:
      "GHK-Cu is a naturally occurring copper-binding tripeptide with well-documented effects on wound healing, collagen and elastin synthesis, angiogenesis, and antioxidant enzyme upregulation in research models.",
    family_slug: "tissue-repair-peptides",
    product_slug: "ghk-cu",
    category: "Regeneration",
    overview: [
      "GHK-Cu (glycyl-L-histidyl-L-lysine copper complex) was first isolated from human plasma by Pickart in 1973. It is a naturally occurring tripeptide that forms a stable complex with copper(II) ions and circulates in human blood, saliva, and urine. Plasma concentrations of GHK decline with age — from approximately 200 ng/mL in young adults to around 80 ng/mL in those over 60 — a pattern that has motivated research into its role in tissue maintenance and repair.",
      "The most extensively documented research applications of GHK-Cu relate to wound healing and dermal tissue remodeling. In cell culture and animal models, GHK-Cu has been shown to stimulate fibroblast proliferation, collagen and glycosaminoglycan synthesis, and the activity of matrix metalloproteinases involved in remodeling aged or damaged extracellular matrix. Studies by Pickart and colleagues, as well as subsequent independent groups, have documented accelerated closure of full-thickness wounds in rodent models.",
      "Beyond structural protein synthesis, GHK-Cu research has revealed effects on antioxidant defense systems. The peptide upregulates superoxide dismutase (SOD) and has been investigated for its role in modulating the ubiquitin-proteasome system to promote clearance of damaged proteins. This combination of pro-synthetic and antioxidant actions has generated interest in GHK-Cu as a model compound for studying the biology of cellular senescence and tissue aging.",
      "GHK-Cu is available for laboratory and research use only. A substantial body of peer-reviewed literature — spanning skin biology, wound healing, neurotrophic factor research, and gene expression analysis — provides a rich foundation for investigators designing experiments in these areas.",
    ],
    mechanism: [
      "GHK-Cu exerts its effects through multiple pathways. The copper component participates in redox reactions and is essential for lysyl oxidase activity, which cross-links collagen and elastin. The peptide carrier facilitates cellular copper uptake and activates downstream signaling cascades, including those involving cAMP and protein kinase A, that modulate gene expression in fibroblasts.",
      "Microarray studies have demonstrated that GHK-Cu influences the expression of over 4,000 genes, with notable effects on pathways related to ECM synthesis, proteasome function, and growth factor signaling (including TGF-β, VEGF, and PDGF). Its antioxidant effects involve upregulation of superoxide dismutase and catalase, providing a mechanistic basis for its observed protective effects in oxidative stress models.",
    ],
    research_applications: [
      "Wound healing and dermal fibroblast biology",
      "Collagen and extracellular matrix synthesis studies",
      "Copper biology and metallopeptide research",
      "Antioxidant enzyme upregulation models",
      "Senescence and cellular aging research",
      "Hair follicle and angiogenesis studies",
    ],
    key_facts: [
      { label: "Structure", value: "Tripeptide Gly-His-Lys + Cu(II)" },
      { label: "Molecular Weight", value: "340.4 Da (peptide); 403.9 Da (Cu complex)" },
      { label: "Endogenous Source", value: "Human plasma, saliva, urine" },
      { label: "Discovery", value: "Pickart, 1973" },
      { label: "Primary Targets", value: "Fibroblasts, ECM, SOD, lysyl oxidase" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    also_known_as: "NNC 26-0161",
    meta_description:
      "Ipamorelin is a selective growth hormone secretagogue and ghrelin receptor agonist. Research documents its highly selective GH-releasing properties with minimal effect on cortisol, prolactin, or ACTH in preclinical models.",
    family_slug: "growth-hormone-secretagogues",
    product_slug: "ipamorelin",
    category: "Growth Hormone Axis",
    overview: [
      "Ipamorelin is a synthetic pentapeptide developed as a growth hormone secretagogue (GHS) and selective agonist of the ghrelin receptor (GHSR-1a). It was synthesized in the late 1990s by Novo Nordisk (compound NNC 26-0161) as part of a research program to develop GHS compounds with improved selectivity profiles. Unlike earlier secretagogues such as GHRP-6 or GHRP-2, ipamorelin demonstrates highly specific stimulation of GH release with minimal cross-activation of other pituitary axes.",
      "The selectivity of ipamorelin is its defining research characteristic. In preclinical studies using rat pituitary cell cultures and in vivo models, ipamorelin produced robust dose-dependent GH release while showing negligible effects on plasma ACTH, cortisol, or prolactin — hormones that are frequently co-stimulated by less selective GHS compounds. This selectivity makes ipamorelin a valuable pharmacological tool for research designs that require isolated modulation of the GH/IGF-1 axis.",
      "Research with ipamorelin has been conducted across several model systems. Studies in aged animal models have documented the ability of ipamorelin to partially restore GH pulse amplitude that declines with aging. Additional research has examined its effects on bone mineral density in animal models, with findings of increased bone formation markers. Ipamorelin has also been used as a reference compound in receptor pharmacology studies characterizing GHSR-1a binding.",
      "Ipamorelin is available for in vitro and in vivo preclinical research use only and is not approved for human therapeutic application. Researchers designing GH axis studies will find ipamorelin's selectivity profile particularly useful for isolating GH-specific effects from confounding changes in stress-axis hormones.",
    ],
    mechanism: [
      "Ipamorelin binds and activates the growth hormone secretagogue receptor 1a (GHSR-1a), a G-protein coupled receptor expressed on somatotroph cells of the anterior pituitary. Receptor activation triggers Gq/11-mediated phospholipase C activation, leading to IP3-mediated calcium release and PKC activation, which collectively stimulate GH granule exocytosis.",
      "Unlike ghrelin, which also activates GHSR-1a, ipamorelin's synthetic pentapeptide structure confers high selectivity for pituitary somatotrophs over other GHSR-expressing tissues, explaining its minimal orexigenic and HPA-activating effects at standard research doses. The compound does not appear to stimulate somatostatin release, distinguishing it mechanistically from GHRH-based secretagogues.",
    ],
    research_applications: [
      "Growth hormone secretagogue receptor (GHSR-1a) pharmacology",
      "GH/IGF-1 axis modulation with high endocrine selectivity",
      "Age-related GH decline and somatopause research",
      "Bone mineral density and skeletal biology models",
      "Comparison studies with GHRP-2, GHRP-6, and hexarelin",
      "Pituitary cell biology and GH secretion studies",
    ],
    key_facts: [
      { label: "Structure", value: "Aib-His-D-2Nal-D-Phe-Lys-NH2 (pentapeptide)" },
      { label: "Molecular Weight", value: "711.9 Da" },
      { label: "Target Receptor", value: "GHSR-1a (ghrelin receptor)" },
      { label: "Selectivity", value: "Minimal ACTH, cortisol, prolactin stimulation" },
      { label: "Developer", value: "Novo Nordisk (NNC 26-0161)" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "cjc-1295",
    name: "CJC-1295 with DAC",
    also_known_as: "CJC-1295 DAC, Drug Affinity Complex GHRH analog",
    meta_description:
      "CJC-1295 with DAC is a long-acting GHRH analog modified with a Drug Affinity Complex to extend plasma half-life to approximately 6–8 days. Research documents sustained GH and IGF-1 elevation in animal models.",
    family_slug: "growth-hormone-secretagogues",
    product_slug: "cjc-1295-with-dac",
    category: "Growth Hormone Axis",
    overview: [
      "CJC-1295 with DAC (Drug Affinity Complex) is a synthetic analog of growth hormone-releasing hormone (GHRH) engineered for extended duration of action. Native GHRH(1-29) has a plasma half-life of only a few minutes due to rapid proteolytic cleavage at the Ala2 position by dipeptidyl peptidase IV (DPP-IV). CJC-1295 incorporates substitutions to resist this cleavage and adds a maleimido-propionic acid (MPA) linker — the Drug Affinity Complex — that enables covalent binding to endogenous albumin, dramatically extending half-life.",
      "The pharmacokinetic profile of CJC-1295 with DAC distinguishes it from all other GHRH analogs in the research literature. Studies in animal models and early phase human pharmacokinetic studies report a plasma half-life of approximately 6–8 days, resulting in sustained elevation of both GH and IGF-1 for up to two weeks following a single administration. This extended action makes CJC-1295 with DAC a valuable research tool for studies requiring prolonged activation of the GH axis without repeated dosing.",
      "Research applications of CJC-1295 with DAC include studies of somatotroph biology, age-related GH decline, and the GH/IGF-1 axis in catabolic conditions. The compound has been compared to pulsatile GHRH administration to understand the physiological significance of GH pulse frequency versus mean GH concentration. In rodent models, CJC-1295 with DAC has been shown to increase lean body mass, reduce adiposity, and improve nitrogen retention in aging animals.",
      "CJC-1295 with DAC is available for research use only. Its unique pharmacokinetic properties make it a particularly useful reference compound for investigators studying GHRH receptor biology, GH axis feedback dynamics, or the development of long-acting peptide therapeutics.",
    ],
    mechanism: [
      "CJC-1295 binds the GHRH receptor (GHRHR), a Gs-protein coupled receptor expressed on pituitary somatotrophs. Receptor activation stimulates adenylyl cyclase, elevating cAMP and activating protein kinase A, which phosphorylates targets involved in GH gene transcription and secretory granule release. The sustained receptor occupancy enabled by albumin binding translates to tonic rather than pulsatile GH release.",
      "The DAC modification (maleimido-propionic acid) reacts with the free thiol group of Cys34 on circulating human serum albumin, creating a covalent adduct that is slowly released over days as albumin turns over. This mechanism is distinct from non-covalent albumin-binding strategies used in other long-acting peptide drugs and confers the characteristic multi-day half-life.",
    ],
    research_applications: [
      "Long-acting GHRH receptor activation studies",
      "GH/IGF-1 axis pharmacokinetics and pharmacodynamics",
      "Somatotroph biology and GH pulse amplitude/frequency research",
      "Albumin-binding drug delivery system research",
      "Body composition and anabolic physiology in animal models",
      "Comparison with native GHRH and other GHRH analogs",
    ],
    key_facts: [
      { label: "Base Sequence", value: "GHRH(1-29) with Ala2→Ser, Met27→Nle substitutions" },
      { label: "Modification", value: "Maleimido-propionic acid DAC linker at Lys12 (MPA-Lys12)" },
      { label: "Half-Life", value: "~6–8 days (via albumin binding)" },
      { label: "Molecular Weight", value: "~3,647 Da" },
      { label: "Target", value: "GHRH receptor (GHRHR)" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    also_known_as: "TH9507, Egrifta (clinical name)",
    meta_description:
      "Tesamorelin is a GHRH(1-44) analog stabilized by a trans-3-hexenoic acid modification. Extensively studied in clinical research for visceral adipose reduction in HIV-associated lipodystrophy. Available for research applications.",
    family_slug: "growth-hormone-secretagogues",
    product_slug: "tesamorelin",
    category: "Growth Hormone Axis",
    overview: [
      "Tesamorelin is a synthetic analog of growth hormone-releasing hormone (GHRH) consisting of the full 44-amino-acid sequence of native GHRH with the addition of a trans-3-hexenoic acid group at the N-terminus. This modification stabilizes the peptide against DPP-IV cleavage at the Ala2 position, extending its biological activity compared to native GHRH while preserving the full receptor-binding sequence.",
      "Tesamorelin is one of the most clinically studied GHRH analogs, having been evaluated in multiple Phase III clinical trials for HIV-associated lipodystrophy (HALS), a condition characterized by visceral fat accumulation. These studies, which led to FDA approval of tesamorelin injection (Egrifta) for HALS in 2010, provide a substantial body of pharmacodynamic data characterizing the compound's effects on the GH axis in human subjects. The clinical data make tesamorelin an important reference compound in GH axis research.",
      "Beyond lipodystrophy research, tesamorelin has been studied in models of cognitive aging. Investigators at Vanderbilt University and other institutions conducted trials examining tesamorelin's effects on executive function and memory in older adults with mild cognitive impairment, with findings suggesting improved performance on cognitive testing and reduced cortical amyloid burden in some analyses. These results have positioned tesamorelin as a research tool in neurodegenerative disease models.",
      "Tesamorelin is available for laboratory research applications. Researchers have access to an unusually rich clinical dataset compared to most research peptides, enabling translation of preclinical findings to established human pharmacodynamic parameters.",
    ],
    mechanism: [
      "Tesamorelin binds the GHRH receptor on pituitary somatotrophs, stimulating cAMP production and protein kinase A-mediated phosphorylation events that promote GH synthesis and pulsatile secretion. Unlike CJC-1295 with DAC, tesamorelin produces physiological GH pulses rather than tonic GH elevation, as it does not have an extended half-life beyond the modified stability of the peptide itself (~30 minutes).",
      "The visceral fat reduction observed in clinical research is attributed to elevated GH stimulating lipolysis specifically in visceral adipose tissue, which has a high density of GH receptors and is more GH-responsive than subcutaneous fat. Downstream IGF-1 elevation also contributes to metabolic effects. The cognitive effects under investigation are hypothesized to involve IGF-1-mediated neuroprotection and GH's direct CNS effects on neurogenesis and amyloid clearance mechanisms.",
    ],
    research_applications: [
      "GHRH receptor pharmacology and GH axis activation",
      "Visceral adipose tissue metabolism and lipolysis models",
      "Cognitive aging and neurodegeneration preclinical models",
      "IGF-1 axis dynamics and metabolic research",
      "Comparison with GHRH(1-29) and other GHRH analogs",
      "Body composition research in metabolic disease models",
    ],
    key_facts: [
      { label: "Sequence", value: "Trans-3-Hex-GHRH(1-44)-NH2" },
      { label: "Molecular Weight", value: "5,136.4 Da" },
      { label: "Stability", value: "DPP-IV resistant; ~30 min half-life" },
      { label: "Clinical Approval", value: "FDA-approved as Egrifta for HALS (2010)" },
      { label: "Target", value: "GHRH receptor (GHRHR)" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "aod9604",
    name: "AOD9604",
    also_known_as: "hGH Fragment 176-191, AOD-9604",
    meta_description:
      "AOD9604 is a modified fragment of the C-terminus of human growth hormone (hGH amino acids 176-191) that retains the fat-metabolizing properties of hGH without binding the GH receptor or elevating IGF-1.",
    family_slug: "growth-hormone-secretagogues",
    product_slug: "aod9604",
    category: "Metabolic",
    overview: [
      "AOD9604 (Anti-Obesity Drug 9604) is a synthetic peptide comprising residues 176-191 of the human growth hormone sequence, with a Tyr0 addition at the N-terminus to improve stability and biological activity. The compound was developed at Monash University in Australia through research by Professor Frank Ng and colleagues, who sought to isolate the lipolytic properties of hGH from its growth-promoting effects mediated through IGF-1.",
      "The research rationale for AOD9604 stems from early observations that the C-terminal domain of hGH contained a region responsible for fat cell regulation distinct from the N-terminal domain responsible for receptor binding and IGF-1 stimulation. By isolating fragment 176-191, researchers created a compound that activates fat metabolism pathways without triggering the mitogenic, insulin-desensitizing, or growth-promoting effects associated with full-length GH. This mechanistic separation makes AOD9604 a valuable research tool for dissecting GH's metabolic versus anabolic functions.",
      "Preclinical research with AOD9604 in rodent obesity models demonstrated dose-dependent reductions in body fat, particularly visceral adiposity, with the compound reducing food intake in some models and increasing fat oxidation rates. A notable feature was the absence of hyperglycemia — a concern with full-length GH — consistent with the absence of IGF-1 stimulation. Phase II clinical trials were conducted in overweight humans, providing pharmacokinetic and safety data that inform current research applications.",
      "AOD9604 is available for research purposes only and is not approved for therapeutic use. It remains a useful model compound for investigators studying adipocyte biology, lipid metabolism signaling, and the pharmacology of GH C-terminal fragments.",
    ],
    mechanism: [
      "AOD9604 does not bind the classical growth hormone receptor (GHR) and does not stimulate IGF-1 production. Its lipolytic effects are mediated through β3-adrenergic receptor pathways and direct effects on adipocyte intracellular signaling, including activation of β3-AR-coupled Gs proteins that elevate cAMP and activate hormone-sensitive lipase (HSL). Research has also implicated PPAR-γ modulation as a secondary mechanism.",
      "In vitro studies in fat cell cultures show that AOD9604 stimulates lipolysis (triglyceride breakdown) and inhibits lipogenesis (fat synthesis) through mechanisms involving PKA activation and downstream phosphorylation of HSL and perilipin. The compound appears to preferentially affect visceral adipocytes, which have higher β-adrenergic receptor density than subcutaneous fat cells.",
    ],
    research_applications: [
      "Adipocyte lipolysis and lipid metabolism research",
      "Visceral fat biology and β3-adrenergic signaling",
      "Dissection of GH anabolic vs. metabolic functions",
      "Obesity model research without hyperglycemic confounders",
      "PPAR-γ modulation studies",
      "GH fragment pharmacology and structure-activity research",
    ],
    key_facts: [
      { label: "Sequence", value: "Tyr-Leu-Arg-Ile-Val-Gln-Cys-Arg-Ser-Val-Glu-Gly-Ser-Cys-Gly-Phe (hGH 176-191 + Tyr0)" },
      { label: "Molecular Weight", value: "1,817.1 Da" },
      { label: "hGH Receptor Binding", value: "Does not bind GHR" },
      { label: "IGF-1 Stimulation", value: "None" },
      { label: "Developer", value: "Metabolic Pharmaceuticals / Monash University" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    also_known_as: "LY3437943, Triple G Agonist",
    meta_description:
      "Retatrutide (LY3437943) is a triple agonist of GLP-1, GIP, and glucagon receptors under active clinical development by Eli Lilly. Phase II trial data shows significant body weight reduction in obese adults. Available for research.",
    family_slug: "glp-1-analogs",
    product_slug: "retatrutide",
    category: "Metabolic",
    overview: [
      "Retatrutide (LY3437943) is a synthetic peptide developed by Eli Lilly and Company that acts as a co-agonist at three G-protein coupled receptors involved in metabolic regulation: the glucagon-like peptide-1 receptor (GLP-1R), glucose-dependent insulinotropic polypeptide receptor (GIPR), and glucagon receptor (GCGR). This triple agonism profile distinguishes it from dual GLP-1/GIP agonists such as tirzepatide and single GLP-1 agonists such as semaglutide, and has generated significant scientific interest.",
      "The clinical data on retatrutide represent some of the most striking weight reduction results reported for any pharmacological agent to date. Phase II trial results published in 2023 in the New England Journal of Medicine reported mean body weight reduction of approximately 17-24% at 48 weeks in adults with obesity, exceeding results reported for tirzepatide at comparable timepoints. The addition of glucagon receptor agonism is hypothesized to contribute to this enhanced weight loss through increased energy expenditure and hepatic glycogenolysis.",
      "From a research perspective, retatrutide is particularly valuable for studying the combined effects of incretin hormones on metabolic physiology. The three receptor systems it activates — GLP-1R, GIPR, and GCGR — each play distinct but interacting roles in glucose homeostasis, energy balance, and lipid metabolism. Research with retatrutide allows investigators to probe the synergistic or additive interactions between these pathways in experimental models.",
      "Retatrutide is currently in Phase III clinical trials and is not approved for human therapeutic use. It is available for preclinical research applications where investigators are studying GLP-1, GIP, or glucagon receptor pharmacology, metabolic disease models, or the comparative pharmacology of incretin-based compounds.",
    ],
    mechanism: [
      "Retatrutide's GLP-1R agonism drives glucose-dependent insulin secretion, reduces glucagon release, slows gastric emptying, and promotes satiety through CNS signaling. The GIPR component contributes incretin-mediated insulin secretion and may also attenuate the nausea associated with GLP-1R agonism when combined. The glucagon receptor agonism increases hepatic glucose production and energy expenditure through cAMP-mediated stimulation of thermogenic pathways.",
      "The net metabolic effect of simultaneous activation of all three receptors appears to be additive or synergistic for weight reduction, with animal studies demonstrating greater fat mass loss than would be predicted from each receptor's individual contribution. The exact molecular basis for this synergy — including potential interactions at the receptor expression level and downstream cross-talk between cAMP signaling cascades — remains an active area of investigation.",
    ],
    research_applications: [
      "GLP-1/GIP/Glucagon triple receptor pharmacology",
      "Metabolic disease and obesity animal models",
      "Comparative incretin biology and receptor synergy studies",
      "Hepatic glucose production and glucagon signaling research",
      "Energy expenditure and thermogenesis models",
      "Novel incretin drug mechanism research",
    ],
    key_facts: [
      { label: "Developer", value: "Eli Lilly and Company (LY3437943)" },
      { label: "Receptor Targets", value: "GLP-1R, GIPR, GCGR (triple agonist)" },
      { label: "Clinical Stage", value: "Phase III (as of 2024)" },
      { label: "Phase II Weight Loss", value: "~17–24% body weight reduction at 48 weeks" },
      { label: "Half-Life", value: "~6 days (fatty acid modification)" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "semax",
    name: "Semax",
    also_known_as: "ACTH(4-7)PGP, Heptapeptide Semax",
    meta_description:
      "Semax is a synthetic heptapeptide derived from the ACTH(4-10) sequence, developed in Russia for neuroprotection research. Studies document BDNF upregulation, NGF stimulation, and cognitive effects in animal models.",
    family_slug: "neuropeptides",
    product_slug: "semax",
    category: "Neurological",
    overview: [
      "Semax is a synthetic heptapeptide (Met-Glu-His-Phe-Pro-Gly-Pro) derived from the ACTH(4-10) sequence but with the C-terminal extension -Pro-Gly-Pro (PGP) that significantly extends its metabolic stability and biological activity compared to the parent ACTH fragment. It was developed at the Institute of Molecular Genetics of the Russian Academy of Sciences in the late Soviet period and has been used as a prescription nootropic in Russia since 1999 under the brand name Semax.",
      "The most extensively documented biological effect of Semax in preclinical literature is stimulation of BDNF (brain-derived neurotrophic factor) and NGF (nerve growth factor) expression in the rat brain. Studies using both systemic and intranasal administration have shown significant increases in BDNF mRNA and protein in the hippocampus and frontal cortex following Semax treatment. These findings have directed research interest toward Semax as a tool for studying neurotrophin-dependent plasticity, memory consolidation, and neuroprotection.",
      "Research in rodent models has also documented cognitive effects of Semax, with studies reporting improved performance on maze-learning tasks, enhanced memory consolidation, and increased attention. Mechanism-focused studies have implicated dopaminergic and serotonergic system modulation in addition to the neurotrophin effects. In stroke models, Semax has been investigated for its ability to reduce infarct volume and improve neurological outcomes when administered within a therapeutic window.",
      "Semax is available for research purposes only and has not been approved by the FDA for any therapeutic application. Investigators in neuroscience research will find particular value in Semax's BDNF-stimulating properties and its well-documented behavioral pharmacology literature.",
    ],
    mechanism: [
      "Semax's neuroprotective and cognition-enhancing effects involve multiple mechanisms. The primary characterized pathway involves enhanced expression of BDNF and activation of its high-affinity receptor TrkB, which mediates downstream signaling through MAP kinase/ERK and PI3K/Akt pathways to promote neuronal survival, synaptic plasticity, and long-term potentiation (LTP). Semax also appears to modulate melanocortin receptor signaling, given its ACTH-derived sequence, though it shows reduced interaction with MC2R (ACTH receptor) compared to the parent hormone.",
      "Additional mechanistic studies have identified effects on the dopaminergic system (increased dopamine turnover in frontal cortex), serotonin metabolism, and nitric oxide synthase activity in cerebrovascular tissue — the latter potentially mediating effects on cerebral blood flow. The PGP extension is critical for metabolic stability and appears to contribute independently to some biological effects, as PGP alone has shown some neuroprotective activity in limited studies.",
    ],
    research_applications: [
      "BDNF and NGF upregulation in CNS research",
      "Neuroprotection and stroke model research",
      "Cognitive function and memory consolidation studies",
      "Melanocortin receptor pharmacology",
      "Dopaminergic and serotonergic system modulation",
      "Cerebrovascular and blood-brain barrier research",
    ],
    key_facts: [
      { label: "Sequence", value: "Met-Glu-His-Phe-Pro-Gly-Pro (ACTH 4-7 + PGP)" },
      { label: "Molecular Weight", value: "887.0 Da" },
      { label: "Primary Effect", value: "BDNF and NGF upregulation" },
      { label: "Administration Routes", value: "Intranasal, subcutaneous (research models)" },
      { label: "Origin", value: "Institute of Molecular Genetics, Russian Academy of Sciences" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "kpv",
    name: "KPV",
    also_known_as: "Lys-Pro-Val, α-MSH C-terminal tripeptide",
    meta_description:
      "KPV (Lys-Pro-Val) is the C-terminal tripeptide of α-melanocyte-stimulating hormone with documented anti-inflammatory properties. Research shows intestinal mucosa protection and NF-κB pathway inhibition in preclinical models.",
    family_slug: "neuropeptides",
    product_slug: "kpv",
    category: "Immunological",
    overview: [
      "KPV (Lys-Pro-Val) is the C-terminal tripeptide of α-melanocyte-stimulating hormone (α-MSH), a peptide hormone derived from proopiomelanocortin (POMC). While α-MSH itself is an endogenous 13-amino-acid peptide with well-characterized roles in pigmentation, inflammation, and energy homeostasis, research has identified the C-terminal KPV sequence as the minimal fragment responsible for α-MSH's anti-inflammatory activity. This specificity has made KPV a useful research tool for studying melanocortin anti-inflammatory pathways independently of pigmentation effects.",
      "The most extensively studied application of KPV is in models of intestinal inflammation. Research groups, particularly those studying inflammatory bowel disease (IBD) models, have documented KPV's ability to protect colonic epithelium and reduce inflammatory parameters in murine colitis models including DSS-induced and TNBS-induced colitis. Studies have shown that KPV reduces neutrophil infiltration, decreases production of pro-inflammatory cytokines (TNF-α, IL-6, IL-1β), and attenuates activation of NF-κB — a central transcription factor in inflammatory signaling.",
      "A notable pharmacokinetic advantage of KPV for gut research is its stability in the gastrointestinal environment and its apparent ability to be absorbed intact through intestinal epithelial cells in some experimental systems. Research has demonstrated that KPV exerts direct anti-inflammatory effects on intestinal epithelial cells in addition to systemic effects, making it relevant to local mucosal biology studies.",
      "KPV is available for laboratory and research use only. Investigators in immunology, gastroenterology research, and melanocortin biology will find extensive primary literature on KPV's receptor interactions and therapeutic potential in inflammatory models.",
    ],
    mechanism: [
      "KPV's anti-inflammatory effects are mediated primarily through melanocortin receptor binding, particularly MC1R and MC3R subtypes expressed on immune cells and gut epithelial cells. Receptor activation couples to Gs proteins that elevate intracellular cAMP, which in turn inhibits NF-κB nuclear translocation and reduces transcription of pro-inflammatory cytokine genes. Research has also identified cAMP-independent effects involving direct interference with IκB kinase (IKK) complex activity.",
      "In gut epithelial research, KPV has been shown to downregulate expression of ICAM-1 and other adhesion molecules on intestinal cells, reducing leukocyte recruitment to inflammatory sites. The compound also appears to promote tight junction integrity, with some evidence of claudin and occludin expression upregulation that could contribute to barrier protection in colitis models.",
    ],
    research_applications: [
      "Inflammatory bowel disease animal models (DSS, TNBS colitis)",
      "NF-κB pathway inhibition and anti-inflammatory signaling",
      "Melanocortin receptor pharmacology (MC1R, MC3R)",
      "Intestinal epithelial barrier integrity research",
      "Cytokine regulation (TNF-α, IL-6, IL-1β) in gut models",
      "α-MSH fragment structure-activity relationship studies",
    ],
    key_facts: [
      { label: "Structure", value: "Lys-Pro-Val (C-terminal tripeptide of α-MSH)" },
      { label: "Molecular Weight", value: "341.4 Da" },
      { label: "Receptors", value: "MC1R, MC3R, MC4R (melanocortin receptors)" },
      { label: "Key Pathway", value: "NF-κB inhibition, cAMP elevation" },
      { label: "Gut Stability", value: "Resistant to GI enzymatic degradation" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "ara-290",
    name: "ARA-290",
    also_known_as: "Cibinetide, Innate Repair Receptor agonist, ERB agonist",
    meta_description:
      "ARA-290 (cibinetide) is a cyclic peptide that selectively activates the Innate Repair Receptor (IRR/EPOR/βCR heteroreceptor) without stimulating erythropoiesis. Research documents neuroprotective and anti-inflammatory effects in multiple models.",
    family_slug: "neuropeptides",
    product_slug: "ara-290",
    category: "Neurological",
    overview: [
      "ARA-290, also known as cibinetide, is a 11-amino-acid cyclic peptide engineered to selectively activate the Innate Repair Receptor (IRR) — a tissue-protective receptor complex distinct from the classical erythropoietin receptor (EPOR). The IRR is a heteroreceptor comprising EPOR and the beta common receptor (βCR), and is expressed on a wide range of non-hematopoietic cells including neurons, macrophages, endothelial cells, and pancreatic beta cells. ARA-290 was designed by Araim Pharmaceuticals to capture the tissue-protective effects of erythropoietin (EPO) without triggering erythropoiesis or other hematopoietic effects.",
      "The scientific rationale behind ARA-290 stems from research by Brines, Cerami, and colleagues demonstrating that EPO has two distinct sets of biological activities: hematopoietic (mediated through the classical EPOR homodimer) and tissue-protective (mediated through the IRR heterodimer). By designing a peptide that binds the IRR selectively, ARA-290 enables tissue-protective signaling without the cardiovascular risks associated with elevated hematocrit from EPO itself.",
      "Research has documented ARA-290's effects in neuropathy models, with several studies from Leiden University Medical Center reporting reduction in pain behavior and nerve fiber loss in animal models of painful peripheral neuropathy, including sarcoidosis-related neuropathy and experimental diabetic neuropathy. Phase II clinical data in sarcoidosis-related small fiber neuropathy showed statistically significant improvements in pain and corneal nerve fiber density — a structural marker of small fiber neuropathy.",
      "ARA-290 is available for research use only. Investigators studying peripheral neuropathy, innate repair signaling, EPO receptor biology, or anti-inflammatory mechanisms will find ARA-290 an important research tool with both extensive preclinical literature and Phase II clinical data.",
    ],
    mechanism: [
      "ARA-290 binds the Innate Repair Receptor (EPOR/βCR heterodimer) and activates downstream Jak2-STAT3 signaling through pathways that differ from those activated by EPO-EPOR homodimer binding. The IRR-mediated signaling is anti-apoptotic and anti-inflammatory, involving STAT3-dependent transcription of survival genes and inhibition of NF-κB-mediated inflammatory signaling.",
      "In neuropathic pain models, ARA-290's mechanism includes modulation of macrophage polarization toward an M2 anti-inflammatory phenotype, reduction of pro-inflammatory cytokines (particularly TNF-α and IL-1β) in the dorsal root ganglion, and direct neurotrophic effects on small sensory fibers expressing IRR. The compound also promotes endothelial cell survival through PI3K/Akt signaling downstream of IRR, potentially contributing to its vascular protective effects.",
    ],
    research_applications: [
      "Innate Repair Receptor (IRR/EPOR/βCR) pharmacology",
      "Peripheral neuropathy models and small fiber neuropathy research",
      "EPO tissue-protective vs. hematopoietic signaling dissection",
      "Anti-inflammatory macrophage polarization studies",
      "Pancreatic beta cell protection in diabetes models",
      "Jak2-STAT3 signaling pathway research",
    ],
    key_facts: [
      { label: "Structure", value: "Cyclic 11-amino-acid peptide" },
      { label: "Molecular Weight", value: "~1,200 Da" },
      { label: "Target", value: "Innate Repair Receptor (EPOR/βCR heterodimer)" },
      { label: "Erythropoietic Activity", value: "None (does not bind EPOR homodimer)" },
      { label: "Clinical Stage", value: "Phase II completed (sarcoidosis neuropathy)" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    also_known_as: "Mitochondrial ORF of the 12S rRNA type-c, Mitochondrial-Derived Peptide",
    meta_description:
      "MOTS-c is a 16-amino-acid mitochondrial-derived peptide (MDP) encoded within the mitochondrial 12S rRNA. Research documents its role in insulin sensitivity, metabolic regulation, exercise adaptation, and AMPK pathway activation.",
    family_slug: "mitochondrial-peptides",
    product_slug: "mots-c",
    category: "Metabolic",
    overview: [
      "MOTS-c (Mitochondrial ORF of the 12S rRNA type-c) is a 16-amino-acid peptide that represents a novel class of signaling molecules: mitochondrial-derived peptides (MDPs). Unlike the vast majority of peptides encoded in the nuclear genome, MOTS-c is translated from a small open reading frame (sORF) within the 12S ribosomal RNA gene of mitochondrial DNA. Its discovery by Kim and colleagues in 2015 (published in Cell Metabolism) established that the mitochondrial genome encodes bioactive peptides with systemic metabolic effects, challenging the conventional understanding of mitochondrial coding capacity.",
      "The metabolic functions of MOTS-c have been studied primarily in the context of insulin sensitivity and glucose homeostasis. In mouse models, systemic MOTS-c administration improved insulin sensitivity, reduced body weight in high-fat diet conditions, and enhanced skeletal muscle glucose uptake. These effects involve AMPK (AMP-activated protein kinase) activation and downstream effects on the folate cycle and methionine metabolism, as well as GLUT4 translocation in muscle cells.",
      "A particularly interesting research application is the role of MOTS-c in exercise physiology. Studies have shown that circulating MOTS-c levels increase in response to exercise in both rodent models and human subjects, with exercise-induced MOTS-c appearing to mediate some of the metabolic adaptations to physical activity. This makes MOTS-c a research tool for studying the crosstalk between mitochondrial function and systemic metabolism during physiological stress.",
      "MOTS-c is also being studied in models of aging, where circulating levels have been reported to decline with age in some populations. Research by Bhanu and colleagues, as well as work from the lab of Pinchas Cohen at USC, has examined MOTS-c as a potential regulator of lifespan and age-related metabolic dysfunction. MOTS-c is available for research use only.",
    ],
    mechanism: [
      "MOTS-c's primary intracellular mechanism involves inhibition of the folate cycle and de novo purine synthesis pathway through direct effects on dihydrofolate reductase (DHFR). This leads to AICAR accumulation, which is a potent AMPK activator. AMPK activation by MOTS-c promotes glucose uptake, fatty acid oxidation, and mitochondrial biogenesis while inhibiting anabolic pathways that consume ATP.",
      "MOTS-c also enters the nucleus following metabolic stress and regulates gene expression through interaction with antioxidant response elements (ARE) and nuclear factor erythroid 2-related factor 2 (Nrf2) pathways. This nuclear signaling role, unusual for a mitochondrially-derived peptide, suggests MOTS-c functions as a retrograde signal from mitochondria to the nucleus during metabolic challenge.",
    ],
    research_applications: [
      "Mitochondrial-derived peptide (MDP) biology",
      "AMPK activation and insulin sensitivity research",
      "Exercise physiology and mitochondrial adaptation models",
      "Age-related metabolic decline and longevity research",
      "Skeletal muscle glucose uptake and GLUT4 trafficking",
      "Folate cycle inhibition and metabolic reprogramming studies",
    ],
    key_facts: [
      { label: "Sequence", value: "MRWQEMGYIFYPRKLR (16 amino acids)" },
      { label: "Genome Origin", value: "Mitochondrial 12S rRNA sORF" },
      { label: "Molecular Weight", value: "2,174.6 Da" },
      { label: "Discovery", value: "Kim et al., Cell Metabolism, 2015" },
      { label: "Primary Target", value: "DHFR (folate cycle) → AMPK activation" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "ss-31",
    name: "SS-31",
    also_known_as: "Elamipretide, MTP-131, Bendavia",
    meta_description:
      "SS-31 (elamipretide) is a mitochondria-targeted tetrapeptide that concentrates in the inner mitochondrial membrane, where it interacts with cardiolipin to protect cristae structure, reduce ROS production, and improve bioenergetic efficiency.",
    family_slug: "mitochondrial-peptides",
    product_slug: "ss-31",
    category: "Mitochondrial",
    overview: [
      "SS-31 (also designated elamipretide, MTP-131, or Bendavia) is a synthetic tetrapeptide (D-Arg-Dmt-Lys-Phe-NH2) that belongs to the Szeto-Schiller family of mitochondria-targeted peptides, developed by Hazel Szeto at Cornell University and Richard Schiller. The peptide's alternating aromatic and basic amino acids confer both cell permeability and a remarkable affinity for the inner mitochondrial membrane (IMM), where it concentrates to concentrations estimated at 1,000-fold over cytoplasmic levels despite its positive charge.",
      "The primary molecular target of SS-31 is cardiolipin, a unique phospholipid found almost exclusively in the IMM where it plays critical structural and functional roles. Cardiolipin is essential for the assembly and stability of the electron transport chain (ETC) supercomplexes and is required for optimal cytochrome c binding during oxidative phosphorylation. Oxidative damage to cardiolipin — a common consequence of mitochondrial ROS overproduction — disrupts ETC supercomplex architecture and impairs ATP synthesis efficiency. SS-31 protects cardiolipin from peroxidation through electron transfer activity and physical stabilization of cristae membrane structure.",
      "Research applications of SS-31 span multiple disease models. In ischemia-reperfusion injury models (cardiac, renal, cerebral), SS-31 administration has consistently reduced infarct size, preserved mitochondrial morphology, and improved functional recovery. Studies in heart failure models have documented improvements in left ventricular function associated with enhanced mitochondrial cristae density and ETC efficiency. In aged animal models, SS-31 has been shown to reverse age-related declines in skeletal muscle mitochondrial function, ATP production, and exercise capacity.",
      "SS-31 advanced to Phase II and Phase III clinical trials for several indications including heart failure and mitochondrial myopathy (MMPOWER study), making it one of the most clinically developed mitochondria-targeted peptides. Investigators have access to both extensive preclinical mechanistic data and clinical pharmacology information. SS-31 is available for research use only.",
    ],
    mechanism: [
      "SS-31 binds cardiolipin through electrostatic interaction with its positively charged lysine and arginine residues combined with hydrophobic interaction via the dimethyltyrosine (Dmt) residue. This dual interaction positions SS-31 within the cardiolipin bilayer where it acts as an electron shuttle to reduce ROS generation at Complex I and III of the ETC. By minimizing cardiolipin oxidation, SS-31 preserves the structural integrity of ETC supercomplexes (respirasomes), maintaining electron transfer efficiency.",
      "Downstream effects include normalization of mitochondrial membrane potential (ΔΨm), reduced cytochrome c release (and thus reduced apoptotic signaling), restored calcium buffering capacity, and improved cristae morphology as measured by electron microscopy. In aging research, SS-31 restores the ratio of fused to fragmented mitochondria, consistent with effects on mitochondrial dynamics in addition to bioenergetics.",
    ],
    research_applications: [
      "Mitochondrial cardiolipin biology and inner membrane research",
      "Ischemia-reperfusion injury models (cardiac, renal, cerebral)",
      "Aging-related mitochondrial dysfunction and bioenergetics",
      "Electron transport chain supercomplex stability studies",
      "Heart failure and cardiomyopathy models",
      "Mitochondria-targeted drug delivery mechanism research",
    ],
    key_facts: [
      { label: "Sequence", value: "D-Arg-Dmt-Lys-Phe-NH2 (tetrapeptide)" },
      { label: "Molecular Weight", value: "639.8 Da" },
      { label: "Target", value: "Cardiolipin (inner mitochondrial membrane)" },
      { label: "Mitochondrial Accumulation", value: "~1,000× enrichment in IMM" },
      { label: "Clinical Stage", value: "Phase II/III completed (heart failure, MMPOWER)" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "nad",
    name: "NAD+",
    also_known_as: "Nicotinamide Adenine Dinucleotide, β-NAD+",
    meta_description:
      "NAD+ (nicotinamide adenine dinucleotide) is an essential coenzyme in cellular energy metabolism, sirtuin activation, and DNA repair. Research documents its role in mitochondrial function, aging biology, and neuroprotection.",
    family_slug: "mitochondrial-peptides",
    product_slug: "nad",
    category: "Metabolic",
    overview: [
      "Nicotinamide adenine dinucleotide (NAD+) is a fundamental coenzyme found in all living cells, where it participates as an electron carrier in oxidative phosphorylation and as a substrate for a diverse class of enzymes that regulate metabolism, stress responses, and aging. NAD+ levels decline with age, caloric excess, and various disease states — a decline that has become a major focus of aging biology research over the past decade.",
      "NAD+ serves two distinct biochemical roles. As a redox carrier, NAD+/NADH couples substrate oxidation to the electron transport chain, driving ATP synthesis in mitochondria. As an enzyme substrate (rather than a cofactor), NAD+ is consumed and regenerated in reactions catalyzed by sirtuins (SIRT1-7), PARP enzymes (involved in DNA repair), and CD38 (an NADase involved in calcium signaling). This dual role means that NAD+ depletion impacts both energy production and regulatory signaling simultaneously.",
      "Research on NAD+ supplementation strategies has grown substantially following seminal work by Guarente, Sinclair, and others demonstrating that restoring NAD+ levels in aged animals could reverse multiple age-associated phenotypes. Studies using NAD+ precursors (NMN, NR) or direct NAD+ have documented effects on mitochondrial function, sirtuin activity, PARP-mediated DNA repair, and inflammatory signaling in both cellular and animal models. NAD+ also plays a central role in the biology of circadian rhythms through NAMPT-mediated synthesis regulation.",
      "NAD+ for research is used in cell-free biochemical assays, enzyme activity measurements, and cellular supplementation studies. Investigators working on sirtuins, PARP biology, mitochondrial metabolism, or aging mechanisms will find NAD+ an essential research reagent. Available for laboratory use only.",
    ],
    mechanism: [
      "In redox metabolism, NAD+ accepts hydride from metabolic substrates (glycolysis, TCA cycle, β-oxidation) to become NADH, which donates electrons to Complex I of the mitochondrial ETC. This electron flow drives the proton gradient used by ATP synthase. As a sirtuin substrate, NAD+ is cleaved during deacetylation reactions, yielding nicotinamide and O-acetyl-ADP-ribose alongside the deacetylated protein target. Sirtuin targets include histones, p53, FOXO transcription factors, and PGC-1α — making NAD+ availability a direct regulator of epigenetic and transcriptional programs.",
      "PARP enzymes (primarily PARP1/2) consume NAD+ to synthesize poly-ADP-ribose (PAR) chains on proteins at DNA damage sites, facilitating repair. Excessive PARP activation during DNA damage can rapidly deplete cellular NAD+ stores, creating a feedforward cycle of mitochondrial dysfunction and cell death. Research with NAD+ supplementation has shown that maintaining NAD+ availability preserves SIRT1 activity and mitochondrial function even under conditions of moderate DNA damage stress.",
    ],
    research_applications: [
      "Sirtuin (SIRT1-7) activity assays and aging biology",
      "PARP enzyme function and DNA repair research",
      "Mitochondrial bioenergetics and oxidative phosphorylation",
      "Circadian rhythm biology and NAMPT pathway research",
      "NAD+ decline in aging models and neuroprotection studies",
      "Cell-free biochemical enzyme assays",
    ],
    key_facts: [
      { label: "Molecular Formula", value: "C₂₁H₂₇N₇O₁₄P₂" },
      { label: "Molecular Weight", value: "663.4 Da" },
      { label: "Key Enzymes", value: "Sirtuins (SIRT1-7), PARPs, CD38" },
      { label: "Redox Pair", value: "NAD+/NADH" },
      { label: "Ubiquity", value: "Present in all living cells" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
  {
    slug: "5-amino-1mq",
    name: "5-Amino-1MQ",
    also_known_as: "5-Amino-1-methylquinolinium, NNMT inhibitor",
    meta_description:
      "5-Amino-1MQ is a small molecule inhibitor of Nicotinamide N-methyltransferase (NNMT), an enzyme upregulated in adipose tissue in obesity. Research documents effects on fat cell size reduction, NAD+ restoration, and metabolic gene expression.",
    family_slug: "mitochondrial-peptides",
    product_slug: "5-amino-1mq",
    category: "Metabolic",
    overview: [
      "5-Amino-1MQ (5-amino-1-methylquinolinium) is a small molecule inhibitor of Nicotinamide N-methyltransferase (NNMT), an enzyme that catalyzes the methylation of nicotinamide using S-adenosyl methionine (SAM) as the methyl donor, producing 1-methylnicotinamide and S-adenosyl homocysteine. NNMT is highly expressed in adipose tissue in obesity and is considered a key regulator of the methionine cycle, cellular methylation capacity, and NAD+ biosynthesis.",
      "The research rationale for 5-Amino-1MQ stems from work by Kraus and colleagues at Duke University demonstrating that NNMT knockout or inhibition in mice produced striking reductions in adipocyte size and fat mass, with protection against diet-induced obesity. The mechanism involves NNMT's role in regulating the SAM/SAH ratio: elevated NNMT activity in obese adipose tissue depletes SAM, impairing histone and DNA methylation in fat cells, while also reducing nicotinamide available for NAD+ synthesis. NNMT inhibition restores these metabolic parameters.",
      "5-Amino-1MQ is membrane-permeable and has been studied in cell culture and mouse models. Research has documented that 5-Amino-1MQ treatment of adipocytes reduces cell size, increases NAD+ content, activates SIRT1, and alters expression of adipogenic transcription factors (PPARγ, C/EBPα). In diet-induced obesity mouse models, 5-Amino-1MQ administration reduced weight gain and improved metabolic parameters without reducing food intake in some study designs.",
      "This compound occupies an interesting intersection between epigenetics research and metabolic pharmacology, as NNMT links the methionine cycle to both NAD+ availability and histone methylation status. 5-Amino-1MQ is available for research use only. The body of literature remains primarily preclinical but is growing rapidly given interest in NNMT as a therapeutic target.",
    ],
    mechanism: [
      "5-Amino-1MQ competitively inhibits NNMT at its nicotinamide-binding site, reducing the conversion of nicotinamide to 1-methylnicotinamide. This inhibition has two key downstream consequences: first, increased availability of nicotinamide substrate for NAD+ biosynthesis via the salvage pathway (nicotinamide → NMN → NAD+), restoring NAD+ levels and sirtuin activity; second, preservation of the SAM/SAH ratio by reducing SAM consumption in NNMT-catalyzed reactions, improving global cellular methylation capacity.",
      "In adipocytes, the combined effects of elevated NAD+ (activating SIRT1) and improved methylation capacity lead to transcriptional reprogramming that reduces lipid storage capacity and promotes a less adipogenic phenotype. SIRT1 activation specifically deacetylates and destabilizes PPARγ and promotes FOXO-mediated transcriptional programs associated with fat cell size reduction.",
    ],
    research_applications: [
      "NNMT inhibitor pharmacology and metabolic epigenetics",
      "Adipocyte biology and fat cell size regulation",
      "NAD+ salvage pathway and sirtuin activation research",
      "Methionine cycle and SAM/SAH ratio studies",
      "Obesity and diet-induced metabolic dysfunction models",
      "Histone methylation in adipose tissue biology",
    ],
    key_facts: [
      { label: "Target Enzyme", value: "Nicotinamide N-methyltransferase (NNMT)" },
      { label: "Molecular Weight", value: "174.2 Da" },
      { label: "Inhibition Type", value: "Competitive at nicotinamide-binding site" },
      { label: "Key Effects", value: "NAD+ restoration, SIRT1 activation, adipocyte size reduction" },
      { label: "Origin Research", value: "Kraus et al., Duke University" },
      { label: "Research Use Only", value: "Not for human or veterinary use" },
    ],
  },
];

export function getTopicBySlug(slug: string): Topic | undefined {
  return TOPICS.find((t) => t.slug === slug);
}
